<!DOCTYPE html>
<html lang="en">
<head>
<meta name="google-site-verification" content="fJTzwsNcz2AtRxQpJZzU7db7TLPdR_lKSAXfyWDtHB4">
<meta name="google-site-verification" content="Xi3WpckDbMBvm1pdlc5XukNoA9uWDmnExIiOeaTOxq0">
{% include seo.dax %}
<link rel="stylesheet" href="/css/style.css">
</head>
<body>
{% include header.dax %}
<main class="container">{{ content }}</main>
{% include footer.dax %}
</body>
</html>