---
layout: base.dax
---
<h1>{{ title }}</h1>
<div>{{ content }}</div>
<div class="row">
{% for post in pagination.items %}
<div><h3><a href="{{ post.url }}">{{ post.title }}</a></h3><p>{{ post.description }}</p></div>
{% endfor %}
</div>
<nav>
{% if pagination.prev_url %}<a href="{{ pagination.prev_url }}">← Prev</a>{% endif %}
 Page {{ pagination.current_page }} / {{ pagination.total_pages }} ({{ pagination.total_items }} posts)
{% if pagination.next_url %}<a href="{{ pagination.next_url }}">Next →</a>{% endif %}
</nav>