<div class="bento-card span-4 trans">
<h3>About</h3>
<img src="{{minimal.about.image}}" 
alt="{{minimal.about.title}}" class="img-thumbnail mt-2 mb-3">
<h3>{{minimal.about.title}}</h3>
<p>{{minimal.about.description}}</p>
<h3 class="mt-5">Lastest Post</h3>
{% for i in collections.posts limit:3 %}
<a href="{{ i.url }}/">
<img class="img-fluid" alt="{{i.title}}" 
width="100%" height="100%"
src="{{i.image}}"/></a> 
<h3>{{i.title}}</h3>
{% endfor %}
<h3 class="mt-5">Tags</h3>
{% for tag in all_tags %}
<a href="/tags/{{ tag }}/" class="btn btn-secondary text-white btn-sm mt-1 mb-1 me-2">
{{tag}}
</a>{% endfor %}
</div>